import {
    HiChartPie,
    HiUser,
    HiUsers,
    HiUserGroup,
    HiInformationCircle,
    HiCog,
    HiOutlineCash,
    HiOutlineTable,
    HiCash,
    HiArrowCircleUp,
} from 'react-icons/hi'
import {
    HiArchiveBox,
    HiBanknotes,
    HiCheckBadge,
    HiClipboardDocumentList,
    HiCog8Tooth,
    HiCreditCard,
    HiCurrencyDollar,
    HiMap,
    HiOutlineCurrencyDollar,
    HiOutlineGlobeAlt,
    HiQuestionMarkCircle,
    HiShoppingCart,
    HiTicket,
    HiUserCircle,
} from 'react-icons/hi2'

export default [
    {
        name: 'Dashboard',
        show: true,
        icon: HiChartPie,
        route: route('dashboard'),
        active: 'dashboard',
        permission: 'view-dashboard',
    },
    {
        name: 'Lokasi',
        show: true,
        icon: HiMap,
        route: route('location.index'),
        active: 'location.*',
        permission: 'view-location',
    },
    {
        name: 'Profile Lokasi',
        show: true,
        icon: HiArchiveBox,
        route: route('location-profile.index'),
        active: 'location-profile.*',
        permission: 'view-location-profile',
    },
    {
        name: 'Voucher',
        show: true,
        icon: HiTicket,
        route: route('voucher.location'),
        active: 'voucher.*',
        permission: 'view-voucher',
    },
    {
        name: 'Sale',
        show: true,
        icon: HiShoppingCart,
        route: route('sale.index'),
        active: 'sale.*',
        permission: 'view-sale',
    },
    {
        name: 'Deposit',
        show: true,
        icon: HiCurrencyDollar,
        route: route('deposit.index'),
        active: 'deposit.*',
        permission: 'view-deposit',
    },
    {
        name: 'Bonus Poin',
        show: true,
        icon: HiOutlineCurrencyDollar,
        route: route('poin-reward.index'),
        active: 'poin-reward.*',
        permission: 'view-poin-reward',
    },
    {
        name: 'Front Home',
        show: true,
        icon: HiOutlineGlobeAlt,
        items: [
            {
                name: 'Banner',
                show: true,
                icon: HiInformationCircle,
                route: route('banner.index'),
                active: 'banner.*',
                permission: 'view-banner',
            },
            {
                name: 'Info',
                show: true,
                icon: HiQuestionMarkCircle,
                route: route('info.index'),
                active: 'info.*',
                permission: 'view-info',
            },
        ],
    },

    {
        name: 'Customer',
        show: true,
        icon: HiUser,
        items: [
            {
                name: 'List',
                show: true,
                icon: HiClipboardDocumentList,
                route: route('customer.index'),
                active: 'customer.*',
                permission: 'view-customer',
            },
            {
                name: 'Atur Level',
                show: true,
                icon: HiArrowCircleUp,
                route: route('customer-level.index'),
                active: 'customer-level.*',
                permission: 'view-customer-level',
            },
            {
                name: 'Atur Affilate',
                show: true,
                icon: HiCog8Tooth,
                route: route('setting.affilate'),
                active: 'setting.affilate',
                permission: 'view-setting-affilate',
            },
            {
                name: 'Verifikasi',
                show: true,
                icon: HiCheckBadge,
                route: route('customer-verification.index'),
                active: 'customer-verification.*',
                permission: 'view-customer-verification',
            },
        ],
    },
    {
        name: 'Mitra WBB',
        show: true,
        icon: HiUserCircle,
        items: [
            {
                name: 'List', //daftar mitra dan stats
                show: true,
                icon: HiClipboardDocumentList,
                route: route('mitra.index'),
                active: 'mitra.*',
                permission: 'view-mitra',
            },
            {
                name: 'Pembayaran Hutang', // daftar pembayaran hutang yang perlu di konfirmasi , dan ada tombol add untuk pembayaran hutang oleh admin
                show: true,
                icon: HiCash,
                route: route('paylater.repay.index'),
                active: 'paylater.repay.*',
                permission: 'view-paylater-repayment',
            },
            {
                name: 'Tambah Limit', // form tambah limit, pilih mitra/customer dan limit
                show: true,
                icon: HiArrowCircleUp,
                route: route('paylater.update.limit'),
                active: 'paylater.update.limit',
                permission: 'update-limit-mitra',
            },
            {
                name: 'Tambah Tenor', // form tambah limit , pilih mitra dengan penambahan tenor
                show: true,
                icon: HiArrowCircleUp,
                route: route('paylater.update.tenor'),
                active: 'paylater.update.tenor',
                permission: 'update-limit-tenor',
            },
        ],
    },
    {
        name: 'Admin',
        show: true,
        icon: HiUser,
        items: [
            {
                name: 'Rule Admin',
                show: true,
                icon: HiUserGroup,
                route: route('roles.index'),
                active: 'roles.*',
                permission: 'view-role',
            },
            {
                name: 'List Admin',
                show: true,
                icon: HiUsers,
                route: route('user.index'),
                active: 'user.*',
                permission: 'view-user',
            },
        ],
    },
    {
        name: 'Akun Pembayaran',
        show: true,
        icon: HiOutlineCash,
        items: [
            {
                name: 'Bank Akun',
                show: true,
                icon: HiBanknotes,
                route: route('account.index'),
                active: 'account.*',
                permission: 'view-account',
            },
            {
                name: 'Payment Gateway',
                show: true,
                icon: HiCog8Tooth,
                route: route('setting.payment'),
                active: 'setting.payment',
                permission: 'view-setting-payment-gateway',
            },
            {
                name: 'Cash / Setor Tunai',
                show: true,
                icon: HiCash,
                route: route('deposit-location.index'),
                active: 'deposit-location.*',
                permission: 'view-deposit-location',
            },
        ],
    },
    {
        name: 'Setting',
        show: true,
        icon: HiCog,
        route: route('setting.index'),
        active: 'setting.index',
        permission: 'view-setting',
    },
]
